// Copyright (c) 2023 Damian Nowakowski. All rights reserved.

#pragma once

#include "CoreMinimal.h"

#if STATS
DECLARE_STATS_GROUP(TEXT("ECF"), STATGROUP_ECF, STATCAT_Advanced);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Actions"), STAT_ECF_ActionsCount, STATGROUP_ECF, ENHANCEDCODEFLOW_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Instances"), STAT_ECF_InstancesCount, STATGROUP_ECF, ENHANCEDCODEFLOW_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Action Objects"), STAT_ECF_ActionsObjectsCount, STATGROUP_ECF, ENHANCEDCODEFLOW_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Async BP Objects"), STAT_ECF_AsyncBPObjectsCount, STATGROUP_ECF, ENHANCEDCODEFLOW_API);
#endif
